
all: run

run:
  src/c01-Analytics Engineering/examples/Example 1-1. SQL procedure to extract data.sql
  src/c01-Analytics Engineering/examples/Example 1-2. An Airflow DAG.py
  src/c01-Analytics Engineering/examples/Example 1-3. A dbt model.sql