dbt_example:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: analytics
      password: analytics
      port: 5432
      dbname: analytics_db
      schema: public
      threads: 4
  target: dev
