# dbt_project.yml - Core project configuration file for Chapter 5

name: 'dbt_advanced_topics'
version: '1.0.0'
config-version: 2

profile: 'dbt_analytics_engineer_book'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_advanced_topics:
    +materialized: view
